# Generated by Django 5.0.1 on 2024-01-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'News table', 'verbose_name_plural': 'News tables'},
        ),
    ]
